version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@11.0.0

parameters:
  alerts-slack-channel:
    type: string
    default: move-a-prisoner-dev-private
  releases-slack-channel:
    type: string
    default: move-a-prisoner-digital

  java-version:
    type: string
    default: "21.0"
  postgres-version:
    type: string
    default: "16.4"

jobs:
  validate:
    executor:
      name: hmpps/java_postgres
      jdk_tag: << pipeline.parameters.java-version >>
      postgres_tag: << pipeline.parameters.postgres-version >>
      postgres_username: "use-of-force"
      postgres_password: "use-of-force"
      postgres_db: "use-of-force"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - hmpps/wait_till_ready_postgres
      - run:
          command: ./gradlew check koverHtmlReport
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
          destination: test-report
      - store_artifacts:
          path: build/reports/kover/html
          destination: test-coverage-report

workflows:
  version: 2
