---
# Per environment values which override defaults in hmpps-uof-data-api/values.yaml

generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: hmpps-uof-data-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
